--drop view commands, if any

DROP schema IF EXISTS s CASCADE;

-- DROP TABLE IF EXISTS Artists CASCADE;

-- DROP TABLE IF EXISTS Countries CASCADE; 

-- DROP TABLE IF EXISTS Songs CASCADE;

-- DROP TABLE IF EXISTS Performs CASCADE;

-- DROP TABLE IF EXISTS PreviousYearsSongs CASCADE;

-- DROP TABLE IF EXISTS UpcomingYearSongs CASCADE;

-- DROP TABLE IF EXISTS Users CASCADE;

-- DROP TABLE IF EXISTS Votes CASCADE;